### ISSUE TITLE
Responsive Code for iframes throws off bootstrap responsive layout.

### ISSUE THREAD

**Issue by psaeger** [Micronet3DPrinting/micronet3dprinting.github.io#4]
Need to figure out what is causing the second column next to the video and calendar to get bumped down. I'll do some more digging.

**Comment by Micronet3DPrinting** [comment]
Resolved youtube issue by switching to built in bootstrap solution.

**Comment by psaeger** [comment]
Resolved youtube video issue with bootstrap integrated classes

**Comment by psaeger** [comment]
Fixed it!
